install:
  - if ! pip3 -V ; then wget -O - https://bootstrap.pypa.io/get-pip.py | python3; fi
  - apt-get install gcc python3-dev lib-ssldev
  - pip3 install -r requirements.txt

docker:
  as_root: true
  image: "coala/rultor-python"

merge:
  fast-forward: only

